describe("sakura-highlight", function()
  local sakura = require("sakura")
  it("should run normaly", function()
    assert.has_no.errors(function()
      sakura.highlight("testhi", {})
    end)
    assert.has_no.errors(function()
      sakura.highlight("testhi", { fg = sakura.palette.black })
    end)
    assert.has_no.errors(function()
      sakura.highlight("testhi", { fg = sakura.palette.black, bg = sakura.palette.red, empha = { "bold", "undercurl" }, guisp = sakura.palette.blue, blend = 0.3 })
    end)
  end)
end)
